sudo: required
services:
  - docker
language: java
jdk:
  - oraclejdk8
install: mvn clean install -f pom.xml -DskipTests=true
before_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
script:
# Dirigible Version (latest | 3.2.5 | 3.3.0 | ...)
  - export RELEASE_VERSION=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`

# Image dirigiblelabs/dirigible-tomcat
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$RELEASE_VERSION
  - docker push $REPO:$RELEASE_VERSION

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=promartio/store-admin
    - secure: "BM2NMluHLsFb49NJyhy1fkxNwqmmtkCbpwek8uTyZEv3/yroNRv7d/Ji6o6D6j+Cl0NInXPv3Y4DaqlKchr0TEooFdngdV404j39lciGH0ALPjWH8WBONqCfrNl74ZUWaqnUDV+w1A50q8N8wuAvBeC2e4+ulon5Fo8sdj2yZaor9kanycBqHyGKhWhGUmz/ui5XkfWW0y8eaA7v8sLI+5TWsZEA6IBQqinXnfHUC2PCmCr+XTn/IrvShUmTlwK+8WAp/7PKhqnmUmEHNBDA0RRN24g326PRCWsTEXsUUx8EmwTt1huCCTuuLrcf56p6IBlXe8OaG5hprranUCAJknuIdprK69ULHRD/eJwgo2d4K34WfdMa4IIi4JKkxsUPypwzRKWQ4gm3Wh84pFJ5X1AVpK3MJsJM1S+SWocAZsTsIpcXrxDkAkC4cTN+dfx7guGo4IlmOHdrb6wFdxL++mIoobd1jIbWNllw9LVb8ggZJt5t98MZQ/CHcWsB/SvA75wp8PCEv9E6Km/H9KFaE2lwasQH709PW/9s2ixln25tEIfbc/MDO2t6yPFNE1TpbVKY79nLYJLGqsltb483KmX2HVAOg/XxbYAUMtb+QGdxQQbbiEt1Q5w31bkgMlajfPUqWhcwO4KUxBx0ZgGnt2M1Zulk9M6H79w/UfibWuY="
    - secure: "jmE57EmO9Bo4z2eTWplgcrE412U1FrXatUwfYPuuVXqaXOffEzboJECuIzMZB19ExboLhuIrxlyS5FcYUCFsFG6UD0qSZr+I+RNYgvL7Inza2b8GzH/a5gnkmCjcojlO/IaWJ2GtfFRIQ2xUduVtJrl9BF3duj+EIE1aI7Tpa4s4OzJwNRvPOBUKCyqzDO+Q7CmrHrVdeq48WCdyg48odk/FKdAdP430O/tI5hq6aN/bDpmITA9TKA/9uHFlGb+2tg9Mvo1pSwZTT5D1WWOoH+tLznWZUnXrNr2uiNP4UT4gUcMYkgd6hPsPKoRVLEVqef36CteQDpRlHNFzaLphW3DQVsb8a0fh3a5cfIKZiEg6viondk1yZxutZlLJA3U/aMmAgRQdmoi2MbJkLbjScTpXAennPVxntjelgmBfi9POHUnpeHukuVE5Msz2wqFkgl9l3SMmTOHs672MIA5fvW2cn1uig7jVCLnYBdxYvwWgVX8Q0liIagW4BPZMND0wJgTKmRHau3q9JiGsLQTuSX01HdcLreJwkYog1arrNTb9fRT8GZjJ+/AjFnBQv9kXDLOVIg392yZ+fvh3zjgraAldT95nN09fXyWnmFLLk6y8knsQtm7cP82lUp6ERuiyw1jBWHV382lLDPrlGIjUgLO3Lx1JknU3SEE4BVOetU4="
